export const ALL_POST_REQUEST = "ALL_POST_REQUEST";
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS";
export const ALL_POST_FAIL = "ALL_POST_FAIL";

export const SINGLE_POST_REQUEST = "SINGLE_POST_REQUEST";
export const SINGLE_POST_SUCCESS = "SINGLE_POST_SUCCESS";
export const SINGLE_POST_FAIL = "SINGLE_POST_FAIL";

export const USER_POST_REQUEST = "USER_POST_REQUEST";
export const USER_POST_SUCCESS = "USER_POST_SUCCESS";
export const USER_POST_FAIL = "USER_POST_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_RESET = "CREATE_POST_RESET";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

// export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
// export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
// export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
// export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

// export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
// export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
// export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

// export const NEW_PASSWORD_REQUEST = "NEW_PASSWORD_REQUEST";
// export const NEW_PASSWORD_SUCCESS = "NEW_PASSWORD_SUCCESS";
// export const NEW_PASSWORD_FAIL = "NEW_PASSWORD_FAIL";

// export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
// export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
// export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

// export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
// export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
// export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

// export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
// export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
// export const UPDATE_USER_RESET = "UPDATE_USER_RESET";
// export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

// export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
